package rs.fizika.inicijalnitest3

object FinalQuestionBank {
    val standard = listOf(
        Question("Pri stalnoj zapremini idealnog gasa, ako se temperatura u kelvinima poveća dva puta, pritisak:", listOf("opadne dva puta","poraste dva puta","ostane isti","poraste četiri puta"),1,"Za V=const važi p/T=const, pa je p proporcionalan apsolutnoj temperaturi."),
        Question("Pri stalnom pritisku idealnog gasa, povećanje apsolutne temperature izaziva:", listOf("smanjenje zapremine","povećanje zapremine","nestanak pritiska","promenu količine supstancije"),1,"Za p=const važi V/T=const."),
        Question("Koja veličina je mikroskopska karakteristika gasa?", listOf("pritisak","zapremina suda","brzina pojedinačnog molekula","temperatura"),2,"Brzina pojedinačnog molekula je mikroskopska veličina, dok su p, V i T makroskopske."),
        Question("Braunovo kretanje predstavlja dokaz:", listOf("mirovanja molekula","toplotnog kretanja čestica","postojanja gravitacije","električne neutralnosti"),1,"Braunovo kretanje nastaje zbog neprekidnih sudara molekula fluida sa sitnim česticama."),
        Question("Apsolutna nula temperature približno iznosi:", listOf("0 °C","-100 °C","-273,15 °C","273,15 °C"),2,"Nula kelvina odgovara približno -273,15 °C."),
        Question("U izohorskom zagrevanju idealnog gasa sva primljena toplota ide na:", listOf("rad gasa","promenu unutrašnje energije","smanjenje pritiska","fazni prelaz obavezno"),1,"Pošto je A=0, iz Q=ΔU+A sledi Q=ΔU."),
        Question("Pri adijabatskom širenju idealnog gasa njegova temperatura obično:", listOf("raste","opada","ostaje stalna","postaje 0 K"),1,"Gas vrši rad bez primanja toplote, pa mu opada unutrašnja energija i temperatura."),
        Question("Drugi zakon termodinamike određuje:", listOf("smer spontanih toplotnih procesa","vrednost gravitacione konstante","Kulonovu silu","gustinu fluida"),0,"Toplota spontano prelazi sa toplijeg na hladnije telo; drugi zakon određuje smer procesa."),
        Question("Toplota spontano prelazi:", listOf("sa hladnijeg na toplije telo","sa toplijeg na hladnije telo","samo u vakuumu","samo pri 0 °C"),1,"Bez spoljnog rada spontani tok toplote je od više ka nižoj temperaturi."),
        Question("Pri kondenzaciji para:", listOf("prima latentnu toplotu","predaje latentnu toplotu","nema razmene energije","uvek raste temperatura"),1,"Pri kondenzaciji supstancija predaje okolini latentnu toplotu."),
        Question("Specifična toplota topljenja ima jedinicu:", listOf("J/kg","J/(kg K)","W/kg","N/kg"),0,"Iz Q=mλ sledi λ=Q/m, pa je jedinica J/kg."),
        Question("Koeficijent linearnog širenja ima jedinicu:", listOf("K","1/K","m/K","J/K"),1,"Iz Δl=αl0ΔT sledi da α ima jedinicu K⁻¹."),
        Question("Pritisak je definisan kao:", listOf("F·S","F/S","S/F","ρV"),1,"Pritisak je normalna sila po jedinici površine: p=F/S."),
        Question("U spojenim sudovima sa istom tečnošću slobodne površine u ravnoteži su:", listOf("na različitim visinama uvek","na istoj visini","zavisne samo od oblika suda","uvek na dnu"),1,"Hidrostatička ravnoteža iste tečnosti daje iste nivoe u spojenim sudovima."),
        Question("Arhimedova sila je usmerena:", listOf("vertikalno naniže","vertikalno naviše","horizontalno","u smeru brzine"),1,"Rezultanta sila pritiska fluida na potopljeno telo usmerena je naviše."),
        Question("Za telo koje tone u tečnosti važi:", listOf("mg>FA","mg<FA","mg=0","FA=0 uvek"),0,"Ako je težina veća od sile potiska, rezultujuća sila je naniže i telo tone."),
        Question("Zapreminski protok fluida jednak je:", listOf("Sv","S/v","v/S","ρgh"),0,"Zapremina koja prođe u jedinici vremena je qV=Sv."),
        Question("Bernulijeva jednačina važi u idealizovanom obliku za:", listOf("stacionarno strujanje idealnog fluida","samo mirnu tečnost","električnu struju","čvrsta tela"),0,"Bernulijeva jednačina povezuje energijske članove duž strujnice idealnog fluida."),
        Question("Površinski napon teži da površinu tečnosti:", listOf("uveća","smanji","ne menja","naelektriše"),1,"Površinska energija je proporcionalna površini, pa sistem teži njenom smanjenju."),
        Question("Kapljica tečnosti u bestežinskom stanju teži obliku:", listOf("kocke","sfere","valjka","ravne ploče"),1,"Sfera ima najmanju površinu za datu zapreminu."),
        Question("Hukov zakon prestaje da važi kada se pređe:", listOf("granica proporcionalnosti/elastičnosti","tačka mržnjenja","atmosferski pritisak","apsolutna nula"),0,"Linearni odnos napona i deformacije važi samo u elastičnoj oblasti."),
        Question("Električni naboj izolovanog sistema:", listOf("uvek raste","uvek opada","održava se","zavisi od mase"),2,"Zakon održanja naboja kaže da je ukupan naboj izolovanog sistema konstantan."),
        Question("Elementarni naboj po intenzitetu je približno:", listOf("1,6·10⁻¹⁹ C","9,81 C","6,67·10⁻¹¹ C","1 C"),0,"Intenzitet naboja protona i elektrona je e≈1,6·10⁻¹⁹ C."),
        Question("Princip superpozicije električnog polja znači da se pojedinačna polja:", listOf("množe","vektorski sabiraju","uvek poništavaju","dele"),1,"Ukupno polje je vektorski zbir polja svih izvora."),
        Question("Ekvipotencijalne površine i silnice električnog polja su:", listOf("paralelne","međusobno normalne","uvek iste","bez veze"),1,"Vektor E je normalan na ekvipotencijalne površine."),
        Question("Električno polje unutar provodnika u elektrostatičkoj ravnoteži je nula jer:", listOf("nema elektrona","slobodni naboji se preraspodele","provodnik nema masu","potencijal je nula svuda u prostoru"),1,"Slobodni naboji se pomeraju dok ne ponište unutrašnje polje."),
        Question("Kapacitet izolovanog provodnika/kondenzatora zavisi prvenstveno od:", listOf("geometrije i sredine","trenutnog naboja samo","trenutnog napona samo","struje"),0,"Kapacitet određuju geometrija i dielektrične osobine sredine."),
        Question("Jedinica električnog kapaciteta je:", listOf("volt","farad","om","amper"),1,"SI jedinica kapaciteta je farad (F)."),
        Question("Energija naelektrisanog kondenzatora nalazi se u:", listOf("električnom polju","masi ploča samo","gravitacionom polju","struji kada je kolo otvoreno"),0,"Energija kondenzatora skladištena je u njegovom električnom polju."),
        Question("Električna struja u metalima nastaje usmerenim kretanjem:", listOf("protona","slobodnih elektrona","neutrona","atoma kao celine"),1,"Nosioci struje u metalima su slobodni elektroni."),
        Question("Amper je jedinica za:", listOf("napon","jačinu struje","otpor","snagu"),1,"SI jedinica jačine električne struje je amper (A)."),
        Question("Volt je jedinica za:", listOf("električni napon","struju","otpor","naboj"),0,"SI jedinica napona je volt (V)."),
        Question("Om je jedinica za:", listOf("snagu","otpor","energiju","kapacitet"),1,"SI jedinica električnog otpora je om (Ω)."),
        Question("Specifični električni otpor zavisi od:", listOf("materijala i temperature","dužine provodnika samo","preseka samo","napona samo"),0,"ρ je osobina materijala i zavisi i od temperature."),
        Question("Idealni ampermetar ima unutrašnji otpor:", listOf("veoma veliki","približno nula","jednak otporu potrošača","beskonačan"),1,"Ampermetar se vezuje redno i treba što manje da menja struju kola."),
        Question("Idealni voltmetar ima unutrašnji otpor:", listOf("približno nula","veoma veliki","uvek 1 Ω","jednak unutrašnjem otporu izvora"),1,"Voltmetar se vezuje paralelno i treba da povlači zanemarljivu struju."),
        Question("Ampermetar se u kolo vezuje:", listOf("redno","paralelno","bez provodnika","samo na izvor"),0,"Kroz ampermetar treba da prođe ista struja koju merimo, zato se vezuje redno."),
        Question("Voltmetar se vezuje:", listOf("redno","paralelno sa elementom","umesto izvora","samo u čvor"),1,"Voltmetar meri razliku potencijala između krajeva elementa i vezuje se paralelno."),
        Question("Električna energija koju potrošač primi za vreme t je:", listOf("UIt","U/I","IR","q/t"),0,"Rad električne struje je A=UIt."),
        Question("Pri kratkom spoju realnog izvora struja je velika jer je:", listOf("spoljašnji otpor veoma mali","EMS nula","unutrašnji otpor beskonačan","napon uvek beskonačan"),0,"Za R≈0 struju ograničava uglavnom mali unutrašnji otpor izvora."),
        Question("Prvo Kirhofovo pravilo matematički izražava:", listOf("ΣI=0 u čvoru","ΣF=0","pV=const","Q=mcΔT"),0,"Algebarski zbir struja u čvoru jednak je nuli."),
        Question("Drugo Kirhofovo pravilo matematički izražava da je u zatvorenoj konturi:", listOf("algebarski zbir promena potencijala nula","struja nula","otpor nula","naboj nestaje"),0,"Pravilo sledi iz zakona održanja energije."),
        Question("Kod redne veze otpornika ekvivalentni otpor je:", listOf("veći od svakog pojedinačnog","manji od najmanjeg","uvek nula","jednak recipročnom zbiru"),0,"Kod redne veze Req=R1+R2+..., pa je veći od svakog pojedinačnog otpora."),
        Question("Kod paralelne veze pozitivnih otpornika ekvivalentni otpor je:", listOf("veći od najvećeg","manji od najmanjeg","zbir svih","uvek 1 Ω"),1,"Paralelno dodavanje grana povećava provodnost, pa Req postaje manji od najmanjeg otpora."),
        Question("Kada kroz otpornik teče struja, električna energija se može pretvarati u:", listOf("toplotnu energiju","naboj","masu elektrona","kapacitet"),0,"Džul-Lencov efekat predstavlja pretvaranje električne energije u toplotu."),
        Question("Snaga izvora ili potrošača meri se u:", listOf("džulima","vatima","kulonima","faradima"),1,"SI jedinica snage je vat (W)."),
        Question("Ako se napon na istom omskom otporniku udvostruči, struja se:", listOf("prepolovi","udvostruči","učetvorostruči","ne menja"),1,"Iz I=U/R, pri R=const, sledi I∝U."),
        Question("Ako se dužina homogenog provodnika udvostruči uz isti presek i temperaturu, otpor se:", listOf("prepolovi","udvostruči","učetvorostruči","ne menja"),1,"R=ρl/S, pa je R proporcionalan dužini."),
        Question("Ako se presek homogenog provodnika udvostruči uz istu dužinu, otpor se:", listOf("udvostruči","prepolovi","učetvorostruči","ne menja"),1,"R=ρl/S, pa je R obrnuto proporcionalan preseku."),
        Question("Pri otvorenom kolu realnog izvora, kada je I=0, priključni napon je:", listOf("0","jednak EMS ε","Ir","uvek 1 V"),1,"Iz U=ε-Ir za I=0 sledi U=ε."),
        Question("Rad gasa pri širenju je pozitivan u konvenciji u kojoj A označava:", listOf("rad koji gas izvrši","rad izvršen nad gasom","samo električni rad","toplotu"),0,"U korišćenoj školskoj konvenciji Q=ΔU+A, A je rad koji gas izvrši."),
        Question("Kod idealnog gasa pri istoj temperaturi teži i lakši molekuli imaju istu srednju:", listOf("brzinu","translacionu kinetičku energiju","količinu kretanja","masu"),1,"Srednja translaciona kinetička energija zavisi samo od apsolutne temperature."),
        Question("Molarna gasna konstanta R povezana je sa Bolcmanovom konstantom preko:", listOf("R=NAk","R=k/NA","R=NA/k","R=Gk"),0,"Važi R=NAk."),
        Question("Pri izotermskom procesu idealnog gasa unutrašnja energija:", listOf("raste","opada","ostaje ista","uvek je nula"),2,"Unutrašnja energija idealnog gasa zavisi od temperature, koja je konstantna."),
        Question("Ako telo pliva delimično potopljeno, prosečna gustina tela je:", listOf("veća od gustine tečnosti","manja od gustine tečnosti","uvek jednaka nuli","nezavisna od tečnosti"),1,"Za delimično potopljeno telo koje pliva prosečna gustina tela je manja od gustine tečnosti."),
        Question("Stoksova sila pri ostalim jednakim uslovima proporcionalna je:", listOf("brzini kuglice","kvadratu brzine","1/brzini","masi suda"),0,"Za laminarno kretanje male kuglice važi F=6πηrv."),
        Question("Električni potencijal u svim tačkama provodnika u elektrostatičkoj ravnoteži je:", listOf("isti","uvek nula","različit u svakoj tački","beskonačan"),0,"Provodnik u elektrostatičkoj ravnoteži je ekvipotencijalan."),
        Question("Rad električne sile duž ekvipotencijalne površine je:", listOf("pozitivan","negativan","nula","beskonačan"),2,"Na ekvipotencijalnoj površini Δφ=0, pa je A=qU=0."),
        Question("Kod pločastog kondenzatora povećanje rastojanja ploča, uz ostalo isto, kapacitet:", listOf("povećava","smanjuje","ne menja","udvostručuje uvek"),1,"C=εS/d, pa povećanje d smanjuje C."),
        Question("Kod pločastog kondenzatora povećanje površine ploča, uz ostalo isto, kapacitet:", listOf("smanjuje","povećava","ne menja","postaje nula"),1,"C=εS/d, pa je kapacitet proporcionalan površini ploča."),
        Question("Elektroni u metalnom provodniku pri postojanju struje imaju:", listOf("samo usmereno kretanje","haotično toplotno i malo usmereno driftno kretanje","potpuno mirovanje","brzinu svetlosti"),1,"Na haotično toplotno kretanje superponuje se mala driftna brzina."),
        Question("Količina naboja koja prođe kroz presek za vreme t pri stalnoj struji I je:", listOf("q=It","q=I/t","q=Ut","q=IR"),0,"Iz I=q/t sledi q=It."),
        Question("Električni rad može se zapisati i kao:", listOf("A=qU","A=q/U","A=U/q","A=IR"),0,"Po definiciji napona, rad pri prenosu naboja q kroz napon U je A=qU."),
        Question("Za dva jednaka otpornika R vezana paralelno ekvivalentni otpor je:", listOf("2R","R","R/2","R²"),2,"1/Req=1/R+1/R=2/R, pa Req=R/2."),
        Question("Za dva jednaka kondenzatora C vezana redno ekvivalentni kapacitet je:", listOf("2C","C","C/2","C²"),2,"1/Ceq=2/C, pa Ceq=C/2."),
        Question("Za dva jednaka kondenzatora C vezana paralelno ekvivalentni kapacitet je:", listOf("C/2","C","2C","1/C"),2,"Kapaciteti se pri paralelnoj vezi sabiraju: Ceq=2C."),
        Question("Unutrašnji otpor izvora izaziva:", listOf("pad priključnog napona kada teče struja","povećanje naboja elektrona","nestanak EMS","uvek beskonačnu struju"),0,"Pri opterećenju važi U=ε-Ir."),
        Question("Kada se potrošač odvoji od realnog izvora, struja je:", listOf("maksimalna","nula","ε/r","uvek 1 A"),1,"Otvoreno kolo nema zatvorenu putanju, pa struja ne teče."),
        Question("U čvoru električnog kola ne može se trajno nagomilavati naboj u stacionarnom režimu, što je osnova:", listOf("prvog Kirhofovog pravila","drugog Njutnovog zakona","Bojlovog zakona","Bernulijeve jednačine"),0,"Održanje naboja u čvoru daje prvo Kirhofovo pravilo."),
        Question("U zatvorenoj električnoj konturi održanje energije je osnova:", listOf("drugog Kirhofovog pravila","Arhimedovog zakona","Hukovog zakona","gasnog zakona"),0,"Algebarski zbir EMS i padova napona u konturi jednak je nuli."),
        Question("Ako je η=0,40, to znači da se u koristan rad pretvara:", listOf("4% primljene toplote","40% primljene toplote","60% primljene toplote","100% primljene toplote"),1,"η=A/Q1=0,40 znači 40% primljene toplote prelazi u rad."),
        Question("Temperaturna razlika od 10 K brojno je jednaka temperaturnoj razlici od:", listOf("10 °C","283 °C","-263 °C","0 °C"),0,"Kelvin i Celzijus imaju isti korak skale, pa su temperaturne razlike brojno jednake."),
        Question("Pri faznom prelazu prvog reda dovedena toplota može da se troši bez promene:", listOf("temperature","agregatnog stanja","unutrašnje energije","strukture supstancije"),0,"Tokom idealizovanog faznog prelaza temperatura ostaje konstantna."),
        Question("Gustina je definisana kao:", listOf("m/V","V/m","mg","F/S"),0,"Gustina je masa po jedinici zapremine: ρ=m/V."),
        Question("U mirnom fluidu sila pritiska na površinu deluje:", listOf("normalno na površinu","uvek horizontalno","uvek vertikalno","tangentno"),0,"Pritisak fluida deluje normalno na svaku površinu."),
        Question("Dinamički član u Bernulijevoj jednačini je:", listOf("ρv²/2","ρgh","pV","mcΔT"),0,"Član ρv²/2 predstavlja kinetičku energiju po jedinici zapremine."),
        Question("Hidrostatički član vezan za visinu u Bernulijevoj jednačini je:", listOf("ρgh","ρv²/2","p/S","qU"),0,"ρgh predstavlja gravitacionu potencijalnu energiju po jedinici zapremine."),
        Question("Relativna deformacija pri istezanju definisana je kao:", listOf("Δl/l0","l0/Δl","F/S","kx"),0,"Relativna deformacija ε=Δl/l0 je bezdimenziona."),
        Question("Mehanički napon u štapu definisan je kao:", listOf("F/S","S/F","F·l","Δl/l"),0,"Mehanički napon σ je sila po površini preseka."),
        Question("Površinski napon ima SI jedinicu:", listOf("N/m","N·m","J/kg","Pa·s samo"),0,"Koeficijent površinskog napona meri se u N/m."),
        Question("Koeficijent dinamičke viskoznosti u Stoksovom zakonu označava se najčešće sa:", listOf("η","ε","λ","α"),0,"Dinamička viskoznost se standardno označava slovom η."),
        Question("Kulonova konstanta u vakuumu približno je:", listOf("9·10⁹ N m²/C²","9,81 N/kg","6,67·10⁻¹¹","8,31 J/(mol K)"),0,"k≈9·10⁹ N m²/C²."),
        Question("Jačina električnog polja definisana je kao:", listOf("E=F/q","E=q/F","E=FU","E=IR"),0,"E je sila po jedinici pozitivnog probnog naboja."),
        Question("Napon je jednak radu električne sile po:", listOf("jedinici naboja","jedinici mase","jedinici vremena","jedinici površine"),0,"U=A/q po intenzitetu za prenos naboja između dve tačke."),
        Question("U homogenom električnom polju silnice su:", listOf("paralelne i jednako razmaknute","kružne","nasumične","uvek radijalne"),0,"Homogeno polje ima isti intenzitet i smer u svakoj tački."),
        Question("Dielektrik između ploča kondenzatora uobičajeno:", listOf("povećava kapacitet","smanjuje površinu ploča","prekida svako električno polje","pretvara kondenzator u otpornik"),0,"Polarizacija dielektrika povećava kapacitet faktorom εr."),
        Question("Kod redne veze otpornika ukupan napon jednak je:", listOf("zbiru padova napona","najmanjem padu","nuli","proizvodu napona"),0,"Iz drugog Kirhofovog pravila sledi U=U1+U2+... za rednu vezu."),
        Question("Kod paralelne veze struja izvora jednaka je:", listOf("zbiru struja grana","struji samo prve grane","nuli","proizvodu struja"),0,"Iz prvog Kirhofovog pravila I=I1+I2+..."),
        Question("Ako je P=UI, pri istom naponu veća struja znači:", listOf("veću snagu","manju snagu","istu snagu","nultu energiju"),0,"Pri U=const snaga je proporcionalna struji."),
        Question("Kilovat-sat je jedinica za:", listOf("energiju","snagu","struju","otpor"),0,"kWh je jedinica energije: snaga puta vreme."),
        Question("Pri istoj snazi, duže vreme rada uređaja znači:", listOf("veću utrošenu energiju","manju energiju","istu energiju","nulti rad"),0,"E=Pt, pa energija raste sa vremenom rada."),
        Question("Ako je rezultujuća sila na malu kuglicu koja pada kroz viskozan fluid nula, ona se kreće:", listOf("graničnom konstantnom brzinom","sa sve većim ubrzanjem","u mirovanju obavezno","brzinom svetlosti"),0,"Kada se težina, potisak i viskozni otpor uravnoteže, ubrzanje je nula i brzina je konstantna."),
        Question("Toričelijeva formula v=√(2gh) pokazuje da brzina isticanja raste sa:", listOf("korenom visine stuba tečnosti","kvadratom visine","1/h","površinom suda obavezno"),0,"Brzina je proporcionalna √h."),
        Question("Ako se gustina tečnosti poveća pri istoj dubini, hidrostatički pritisak:", listOf("raste","opada","ne menja","postaje nula"),0,"p=ρgh, pa je pritisak proporcionalan gustini."),
        Question("Ako se poluprečnik kapilare smanji, visina kapilarnog podizanja tečnosti koja kvasi zid:", listOf("raste","opada","ne menja","postaje nula"),0,"h je obrnuto proporcionalno poluprečniku kapilare."),
        Question("Kod idealne toplotne mašine rad u ciklusu jednak je:", listOf("Q1-Q2","Q1+Q2","Q2-Q1 uvek","nuli za svaku mašinu"),0,"Po ciklusu ΔU=0, pa je A=Q1-Q2."),
        Question("Karnoov stepen korisnog dejstva raste kada se, uz isto T2:", listOf("poveća T1","smanji T1","izjednače T1 i T2","T1 postavi na 0 K"),0,"η=1-T2/T1; veće T1 pri istom T2 povećava η."),
        Question("Za jednoatomski idealni gas molarni toplotni kapacitet pri stalnoj zapremini je povezan sa promenom unutrašnje energije preko:", listOf("ΔU=nCvΔT","ΔU=pV uvek","ΔU=0 uvek","ΔU=qU"),0,"Promena unutrašnje energije idealnog gasa može se pisati ΔU=nCvΔT."),
        Question("Masa jednog mola supstancije naziva se:", listOf("molarna masa","gustina","specifična toplota","molarna zapremina"),0,"Molarna masa M=m/n predstavlja masu jednog mola."),
        Question("Avogadrov broj predstavlja broj čestica u:", listOf("jednom molu","jednom kilogramu svake supstancije","jednom litru uvek","jednom kulonu"),0,"NA≈6,02·10²³ mol⁻¹ je broj čestica u jednom molu."),
        Question("Pri povećanju broja molekula u istoj zapremini i na istoj temperaturi pritisak idealnog gasa:", listOf("raste","opada","ne menja","postaje nula"),0,"Iz pV=NkT, za V i T konstantne, p je proporcionalan N."),
        Question("Ako je spoljašnji otpor mnogo veći od unutrašnjeg otpora izvora, priključni napon je:", listOf("približno jednak EMS","približno nula","uvek dvostruko veći od EMS","negativan"),0,"Za malu struju pad Ir je mali, pa U≈ε."),
        Question("Korisna snaga na spoljašnjem otporniku može se zapisati kao:", listOf("P=I²R","P=I²r samo","P=ε/r","P=q/t"),0,"Za potrošač važi P=UI=I²R."),
        Question("Gubitak snage unutar realnog izvora iznosi:", listOf("I²r","I²R","εI bez ostatka","qU"),0,"Na unutrašnjem otporu izvora disipira se snaga I²r."),
        Question("Električno polje tačkastog naboja opada sa rastojanjem kao:", listOf("1/r²","1/r","r","r²"),0,"E=k|Q|/r²."),
        Question("Potencijal tačkastog naboja opada sa rastojanjem kao:", listOf("1/r","1/r²","r","r²"),0,"φ=kQ/r."),
        Question("Ako je probni naboj pozitivan, sila električnog polja ima:", listOf("isti smer kao E","suprotan smer od E uvek","uvek vertikalan smer","nulti intenzitet"),0,"Iz F=qE za q>0 sledi isti smer F i E."),
        Question("Ako je probni naboj negativan, sila električnog polja ima:", listOf("suprotan smer od E","isti smer kao E","uvek horizontalan smer","nulti intenzitet"),0,"Za q<0 vektor F=qE ima suprotan smer od E."),
        Question("Rad električnog polja pri kretanju pozitivnog naboja u smeru silnica je povezan sa promenom potencijalne energije tako da ona:", listOf("opada","raste","ostaje ista uvek","postaje beskonačna"),0,"Kada polje vrši pozitivan rad, električna potencijalna energija opada."),
        Question("Pri punjenju kondenzatora izvor vrši rad koji se delom skladišti kao:", listOf("energija električnog polja","gravitaciona energija","masa naboja","magnetna energija obavezno"),0,"Naelektrisan kondenzator skladišti energiju EC=CU²/2."),
        Question("Za stalnu jednosmernu struju kroz isti presek provodnika, količina naboja u jednakim vremenskim intervalima je:", listOf("jednaka","sve manja","sve veća","nasumična"),0,"Kod I=const važi Δq=IΔt."),
        Question("Omov zakon U=RI direktno važi za:", listOf("omske provodnike pri nepromenjenim fizičkim uslovima","svaki nelinearni element bez ograničenja","idealni gas","kondenzator bez struje"),0,"Omski provodnik ima linearnu U-I karakteristiku pri konstantnoj temperaturi."),
        Question("Nagib U-I grafika omskog provodnika predstavlja:", listOf("otpor R","snagu P","naboj q","kapacitet C"),0,"Iz U=RI sledi da je nagib ΔU/ΔI=R."),
        Question("Nagib I-U grafika omskog provodnika predstavlja:", listOf("provodnost 1/R","otpor R","energiju","EMS"),0,"Iz I=U/R sledi ΔI/ΔU=1/R."),
        Question("Pri rednoj vezi dva otpornika veći pad napona je na:", listOf("većem otporu","manjem otporu","oba su uvek jednaka","izvoru samo"),0,"Struja je ista, a U=IR, pa veći R daje veći pad napona."),
        Question("Pri paralelnoj vezi dve grane veća struja teče kroz:", listOf("manji otpor","veći otpor","obe uvek isto","nijednu"),0,"Napon je isti, a I=U/R, pa manji R daje veću struju.")
    ).take(100)

    val basic = listOf(
        Question("Gas pri 100 kPa ima 3 L. Izotermski se proširi na 6 L. Novi pritisak je:", listOf("25 kPa","50 kPa","100 kPa","200 kPa"),1,"p1V1=p2V2; p2=100·3/6=50 kPa."),
        Question("Gas primi 500 J toplote i izvrši 200 J rada. ΔU je:", listOf("300 J","700 J","200 J","-300 J"),0,"ΔU=Q-A=500-200=300 J."),
        Question("Za zagrevanje 1 kg vode za 10 K, c=4200 J/(kgK), potrebno je:", listOf("4,2 kJ","42 kJ","420 kJ","4200 kJ"),1,"Q=mcΔT=1·4200·10=42000 J=42 kJ."),
        Question("Za topljenje 0,5 kg leda, λ=334 kJ/kg, potrebno je:", listOf("16,7 kJ","167 kJ","334 kJ","668 kJ"),1,"Q=mλ=0,5·334=167 kJ."),
        Question("Pri p=200 kPa gas se proširi za 2 L. Rad je:", listOf("40 J","400 J","4000 J","0 J"),1,"A=pΔV=200000·0,002=400 J."),
        Question("Mašina primi 1000 J i izvrši 300 J rada. η je:", listOf("3%","30%","70%","300%"),1,"η=A/Q1=300/1000=0,30=30%."),
        Question("Na dubini 2 m u vodi, ρ=1000 kg/m³ i g=10 m/s², hidrostatički pritisak je:", listOf("2 kPa","20 kPa","200 kPa","2000 kPa"),1,"p=ρgh=1000·10·2=20000 Pa=20 kPa."),
        Question("Telo zapremine 0,004 m³ potpuno je u vodi. Uz g=10 m/s², FA je:", listOf("4 N","40 N","400 N","4000 N"),1,"FA=ρgV=1000·10·0,004=40 N."),
        Question("Cev se sužava sa 10 cm² na 5 cm². Ako je v1=1 m/s, v2 je:", listOf("0,5 m/s","1 m/s","2 m/s","5 m/s"),2,"S1v1=S2v2; v2=10/5·1=2 m/s."),
        Question("Opruga k=100 N/m istegnuta je 5 cm. Sila je:", listOf("0,5 N","5 N","50 N","500 N"),1,"x=0,05 m; F=kx=5 N."),
        Question("Opruga k=200 N/m istegnuta je 10 cm. Elastična energija je:", listOf("0,1 J","1 J","10 J","100 J"),1,"E=kx²/2=200·0,1²/2=1 J."),
        Question("Naboji 1 μC i 1 μC na 0,1 m deluju silom:", listOf("0,09 N","0,9 N","9 N","90 N"),1,"F=9·10⁹·10⁻¹²/0,01=0,9 N."),
        Question("Ako je U=100 V i d=0,02 m, homogeno polje E je:", listOf("50 V/m","500 V/m","5000 V/m","50000 V/m"),2,"E=U/d=100/0,02=5000 V/m."),
        Question("Naboj 2 μC prolazi kroz napon 500 V. Rad je:", listOf("0,1 mJ","1 mJ","10 mJ","100 mJ"),1,"A=qU=2·10⁻⁶·500=10⁻³ J=1 mJ."),
        Question("Kondenzator 10 μF na 50 V ima naboj:", listOf("0,05 mC","0,5 mC","5 mC","50 mC"),1,"q=CU=10·10⁻⁶·50=0,5 mC."),
        Question("Kondenzator 20 μF na 100 V ima energiju:", listOf("0,01 J","0,1 J","1 J","10 J"),1,"E=CU²/2=20·10⁻⁶·10000/2=0,1 J."),
        Question("Otpornik 10 Ω na 20 V provodi struju:", listOf("0,5 A","2 A","10 A","200 A"),1,"I=U/R=20/10=2 A."),
        Question("Kroz otpornik 5 Ω teče 2 A. Napon je:", listOf("2,5 V","7 V","10 V","20 V"),2,"U=RI=5·2=10 V."),
        Question("Uređaj na 220 V vuče 2 A. Snaga je:", listOf("110 W","220 W","440 W","880 W"),2,"P=UI=220·2=440 W."),
        Question("Otpornik 4 Ω kroz koji teče 3 A razvija snagu:", listOf("12 W","24 W","36 W","48 W"),2,"P=I²R=9·4=36 W."),
        Question("Dva otpornika 2 Ω i 3 Ω redno daju:", listOf("1,2 Ω","5 Ω","6 Ω","0,5 Ω"),1,"Req=2+3=5 Ω."),
        Question("Dva jednaka otpornika 8 Ω paralelno daju:", listOf("2 Ω","4 Ω","8 Ω","16 Ω"),1,"Za dva jednaka otpornika Req=R/2=4 Ω."),
        Question("Kondenzatori 2 μF i 3 μF paralelno daju:", listOf("1,2 μF","5 μF","6 μF","0,5 μF"),1,"Ceq=C1+C2=5 μF."),
        Question("Dva jednaka kondenzatora 10 μF redno daju:", listOf("5 μF","10 μF","20 μF","100 μF"),0,"Za dva jednaka redno vezana kondenzatora Ceq=C/2=5 μF."),
        Question("Izvor ε=6 V, r=1 Ω, R=5 Ω daje struju:", listOf("0,5 A","1 A","5 A","6 A"),1,"I=ε/(R+r)=6/6=1 A."),
        Question("Izvor ε=12 V, r=1 Ω daje I=2 A. Priključni napon je:", listOf("8 V","10 V","12 V","14 V"),1,"U=ε-Ir=12-2=10 V."),
        Question("Kroz presek za 5 s prođe 10 C. Struja je:", listOf("0,5 A","2 A","5 A","50 A"),1,"I=q/t=10/5=2 A."),
        Question("Struja 3 A teče 4 s. Prođe naboj:", listOf("0,75 C","7 C","12 C","24 C"),2,"q=It=3·4=12 C."),
        Question("Otpornici 6 Ω i 3 Ω paralelno daju:", listOf("2 Ω","3 Ω","4,5 Ω","9 Ω"),0,"Req=6·3/(6+3)=2 Ω."),
        Question("Kroz 10 Ω teče 1 A tokom 10 s. Toplota je:", listOf("10 J","100 J","1000 J","1 J"),1,"Q=I²Rt=1·10·10=100 J."),
        Question("Na površinu 0,02 m² deluje normalna sila 100 N. Pritisak je:", listOf("50 Pa","500 Pa","5000 Pa","50000 Pa"),2,"p=F/S=100/0,02=5000 Pa."),
        Question("Telo mase 2 kg i zapremine 0,001 m³ ima gustinu:", listOf("200 kg/m³","2000 kg/m³","20 kg/m³","2 kg/m³"),1,"ρ=m/V=2/0,001=2000 kg/m³."),
        Question("Ako je η=25% i Q1=800 J, rad mašine je:", listOf("100 J","200 J","400 J","600 J"),1,"A=ηQ1=0,25·800=200 J."),
        Question("Gas pri stalnoj zapremini ima 100 kPa na 300 K. Na 600 K pritisak je:", listOf("50 kPa","100 kPa","200 kPa","600 kPa"),2,"p/T=const, pa p2=100·600/300=200 kPa."),
        Question("Gas pri stalnom pritisku zauzima 2 L na 300 K. Na 450 K zapremina je:", listOf("1 L","2 L","3 L","4 L"),2,"V/T=const; V2=2·450/300=3 L.")
    )

    val medium = listOf(
        Question("Dva mola idealnog gasa na 300 K zauzimaju 0,050 m³. Uz R=8,31, pritisak je približno:", listOf("10 kPa","100 kPa","200 kPa","1 MPa"),1,"p=nRT/V=2·8,31·300/0,05≈99,7 kPa."),
        Question("Gas primi 1200 J, a unutrašnja energija mu poraste 750 J. Rad gasa je:", listOf("450 J","750 J","1200 J","1950 J"),0,"A=Q-ΔU=1200-750=450 J."),
        Question("Gas se pri 250 kPa proširi sa 1 L na 5 L. Rad je:", listOf("100 J","500 J","1000 J","1250 J"),2,"ΔV=0,004 m³; A=250000·0,004=1000 J."),
        Question("Mašina primi 3000 J i ima η=40%. Hladnjaku preda:", listOf("600 J","1200 J","1800 J","2400 J"),2,"A=0,4·3000=1200 J; Q2=3000-1200=1800 J."),
        Question("Karnoova mašina radi između 600 K i 300 K. ηmax je:", listOf("25%","50%","75%","100%"),1,"η=1-300/600=0,5=50%."),
        Question("0,5 kg vode, c=4200 J/(kgK), primi 21 kJ. Porast temperature je:", listOf("5 K","10 K","20 K","42 K"),1,"ΔT=Q/(mc)=21000/(0,5·4200)=10 K."),
        Question("Hidraulična presa: S1=10 cm², S2=250 cm², F1=80 N. F2 je:", listOf("200 N","800 N","1600 N","2000 N"),3,"F2=F1S2/S1=80·25=2000 N."),
        Question("Telo mase 3 kg i zapremine 0,004 m³ potpuno je u vodi, g=10. Rezultujuća sila po intenzitetu i smeru je:", listOf("10 N naviše","10 N naniže","30 N naviše","40 N naniže"),0,"FA=40 N, mg=30 N, pa Fres=10 N naviše."),
        Question("Cev se sužava sa 12 cm² na 3 cm². Ako je v1=1,5 m/s, v2 je:", listOf("3 m/s","4,5 m/s","6 m/s","12 m/s"),2,"v2=S1v1/S2=12·1,5/3=6 m/s."),
        Question("Idealna tečnost ističe iz otvora 3,2 m ispod površine, g=10. Brzina je:", listOf("4 m/s","8 m/s","16 m/s","32 m/s"),1,"v=√(2gh)=√64=8 m/s."),
        Question("Opruga k=500 N/m ima elastičnu energiju 1 J. Izduženje je približno:", listOf("2 cm","4,5 cm","10 cm","20 cm"),1,"x=√(2E/k)=√(2/500)≈0,0447 m=4,5 cm."),
        Question("Naboji 4 μC i 5 μC udaljeni 0,20 m deluju silom:", listOf("0,45 N","4,5 N","45 N","450 N"),1,"F=9·10⁹·20·10⁻¹²/0,04=4,5 N."),
        Question("Kulonova sila je F na rastojanju r. Ako oba naboja udvostručimo, a rastojanje udvostručimo, sila je:", listOf("F/4","F","2F","4F"),1,"Brojilac raste 4 puta, imenilac 4 puta, pa sila ostaje F."),
        Question("Naboj 3 μC u polju E=2·10⁴ N/C trpi silu:", listOf("0,006 N","0,06 N","0,6 N","6 N"),1,"F=qE=3·10⁻⁶·2·10⁴=0,06 N."),
        Question("Potencijal tačkastog naboja Q=2 nC na r=0,20 m je, k=9·10⁹:", listOf("9 V","90 V","900 V","0,9 V"),1,"φ=kQ/r=9·10⁹·2·10⁻⁹/0,2=90 V."),
        Question("Elektron po intenzitetu naboja e=1,6·10⁻¹⁹ C prođe kroz 1000 V. Promena energije po intenzitetu je:", listOf("1,6·10⁻²² J","1,6·10⁻¹⁹ J","1,6·10⁻¹⁶ J","1,6·10⁻¹³ J"),2,"|A|=eU=1,6·10⁻¹⁹·1000=1,6·10⁻¹⁶ J."),
        Question("Kondenzatori 6 μF i 3 μF redno su na 18 V. Ekvivalentni kapacitet i ukupan naboj su:", listOf("2 μF i 36 μC","9 μF i 162 μC","3 μF i 54 μC","18 μF i 324 μC"),0,"Ceq=6·3/(6+3)=2 μF; q=CeqU=36 μC."),
        Question("Kondenzatori 4 μF i 6 μF paralelno su na 50 V. Ukupna energija je:", listOf("0,00125 J","0,0125 J","0,125 J","1,25 J"),1,"Ceq=10 μF; E=CeqU²/2=10·10⁻⁶·2500/2=0,0125 J."),
        Question("Otpornici 2 Ω i 4 Ω redno su na 12 V. Struja i pad napona na 4 Ω su:", listOf("2 A i 8 V","3 A i 6 V","6 A i 4 V","1 A i 4 V"),0,"R=6 Ω, I=12/6=2 A, U4=2·4=8 V."),
        Question("Otpornici 6 Ω i 3 Ω paralelno su na 12 V. Ukupna struja je:", listOf("2 A","4 A","6 A","8 A"),2,"I1=2 A, I2=4 A, ukupno 6 A."),
        Question("Otpornici 2 Ω i 4 Ω su redno, kombinacija paralelno sa 3 Ω. Ekvivalentni otpor je:", listOf("2 Ω","3 Ω","6 Ω","9 Ω"),0,"Redna grana je 6 Ω; 6 Ω paralelno sa 3 Ω daje 2 Ω."),
        Question("Izvor ε=15 V, r=1 Ω priključen na R=4 Ω. Struja i priključni napon su:", listOf("3 A i 12 V","3 A i 15 V","5 A i 10 V","2 A i 13 V"),0,"I=15/5=3 A; U=IR=12 V."),
        Question("Izvor ε=10 V, r=2 Ω daje struju 2 A. Spoljašnji otpor je:", listOf("1 Ω","2 Ω","3 Ω","5 Ω"),2,"R+r=ε/I=5 Ω, pa R=3 Ω."),
        Question("U čvor ulaze 5 A i 2 A, a izlaze 3 A, 1 A i I. I je:", listOf("1 A","2 A","3 A","4 A"),2,"5+2=3+1+I, pa I=3 A."),
        Question("U konturi su ε=12 V i dva redna otpornika 2 Ω i 4 Ω bez unutrašnjeg otpora. Struja je:", listOf("1 A","2 A","3 A","6 A"),1,"I=ε/(R1+R2)=12/6=2 A."),
        Question("Grejač 2 kW radi 45 min. Energija je:", listOf("0,75 kWh","1,5 kWh","2 kWh","90 kWh"),1,"45 min=0,75 h; E=2·0,75=1,5 kWh."),
        Question("Na 230 V uređaj snage 920 W vuče struju:", listOf("2 A","4 A","8 A","230 A"),1,"I=P/U=920/230=4 A."),
        Question("Otpornik na 100 V razvija 500 W. Njegov otpor je:", listOf("5 Ω","20 Ω","50 Ω","200 Ω"),1,"R=U²/P=10000/500=20 Ω."),
        Question("Kroz 8 Ω tokom 5 min teče 2 A. Oslobođena toplota je:", listOf("960 J","4800 J","9600 J","19200 J"),2,"t=300 s; Q=I²Rt=4·8·300=9600 J."),
        Question("Žica istog materijala postane dva puta duža i presek joj se prepolovi. Otpor postaje:", listOf("R","2R","4R","R/4"),2,"R∝l/S; faktor je 2/(1/2)=4."),
        Question("Dva ista izvora EMS 1,5 V idealno vezana redno daju ukupnu EMS:", listOf("0,75 V","1,5 V","3 V","6 V"),2,"Pri saglasnoj rednoj vezi EMS se sabiraju: 3 V."),
        Question("Ako je priključni napon izvora 9 V pri struji 1,5 A, a ε=12 V, unutrašnji otpor je:", listOf("1 Ω","2 Ω","3 Ω","6 Ω"),1,"r=(ε-U)/I=(12-9)/1,5=2 Ω."),
        Question("Kondenzator ima energiju 0,2 J pri naponu 200 V. Kapacitet je:", listOf("1 μF","10 μF","20 μF","100 μF"),1,"C=2E/U²=0,4/40000=10⁻⁵ F=10 μF."),
        Question("Na rastojanju r polje tačkastog naboja je 3600 N/C. Na 3r je:", listOf("400 N/C","1200 N/C","10800 N/C","32400 N/C"),0,"E∝1/r², pa E2=3600/9=400 N/C."),
        Question("Gas pri 150 kPa i 2 L pređe izotermski na 75 kPa. Konačna zapremina je:", listOf("1 L","2 L","4 L","8 L"),2,"p1V1=p2V2; V2=150·2/75=4 L.")
    )
}
