package rs.fizika.inicijalnitest3

object QuestionBank {
    val all = listOf(
        Question("Koja tvrdnja najbolje opisuje idealni gas?", listOf("Molekuli miruju", "Molekuli se haotično kreću i sudari su elastični", "Molekuli imaju veliku zapreminu", "Međumolekulske sile su uvek velike"), 1, "U modelu idealnog gasa molekuli se haotično kreću, njihova sopstvena zapremina se zanemaruje, a sudari su elastični."),
        Question("Srednja kinetička energija molekula idealnog gasa proporcionalna je:", listOf("zapremini", "pritisku", "apsolutnoj temperaturi", "masi suda"), 2, "Za translaciono kretanje molekula važi ⟨Ek⟩ = 3kT/2."),
        Question("Koja je jednačina stanja idealnog gasa?", listOf("pV = nRT", "p/T = nR", "V = pRT", "p = nV/T"), 0, "Osnovna jednačina stanja idealnog gasa je pV = nRT."),
        Question("U izotermskom procesu za istu količinu idealnog gasa važi:", listOf("pV = const.", "p/T = const.", "V/T = const.", "pV/T = 0"), 0, "Pri T = const. Bojl-Mariotov zakon daje pV = const."),
        Question("U izobarskom procesu važi:", listOf("pV = const.", "V/T = const.", "p/T = const.", "V = const."), 1, "Pri konstantnom pritisku zapremina idealnog gasa proporcionalna je apsolutnoj temperaturi."),
        Question("U izohorskom procesu važi:", listOf("p/T = const.", "V/T = const.", "pV = const.", "p = const."), 0, "Pri V = const. pritisak je proporcionalan apsolutnoj temperaturi."),
        Question("Prvi zakon termodinamike, ako je A rad koji izvrši gas, glasi:", listOf("Q = ΔU + A", "Q = A - ΔU", "ΔU = Q + A", "A = Q + ΔU"), 0, "Primljena toplota menja unutrašnju energiju sistema i/ili se pretvara u rad gasa."),
        Question("U izohorskom procesu rad gasa je:", listOf("maksimalan", "jednak Q", "jednak nuli", "uvek negativan"), 2, "Pošto nema promene zapremine, A = pΔV = 0."),
        Question("Za idealni gas u izotermskom procesu važi:", listOf("ΔU = 0", "A = 0", "Q = 0", "p = const."), 0, "Unutrašnja energija idealnog gasa zavisi od temperature, pa pri T = const. važi ΔU = 0."),
        Question("Stepen korisnog dejstva toplotne mašine je:", listOf("η = Q1/A", "η = A/Q1", "η = Q2/A", "η = Q1/Q2"), 1, "Stepen korisnog dejstva je odnos korisnog rada i primljene toplote: η = A/Q1."),
        Question("Karnoov maksimalni stepen korisnog dejstva je:", listOf("1 - T2/T1", "T2/T1", "1 + T2/T1", "T1/T2"), 0, "Za temperature izražene u kelvinima važi ηmax = 1 - T2/T1."),
        Question("Tokom topljenja čiste supstancije pri stalnom pritisku temperatura:", listOf("raste", "opada", "ostaje približno konstantna", "uvek je 0 °C"), 2, "Dovedena toplota se troši na fazni prelaz, a ne na povećanje temperature."),
        Question("Toplota potrebna za topljenje mase m jednaka je:", listOf("mcΔT", "mλ", "mL", "mgh"), 1, "Za topljenje važi Q = mλ."),
        Question("Linearno toplotno širenje opisuje izraz:", listOf("Δl = αl0ΔT", "Δl = l0/αΔT", "Δl = αΔT/l0", "Δl = αl0/T"), 0, "Promena dužine je proporcionalna početnoj dužini i promeni temperature."),
        Question("Hidrostatički pritisak u tečnosti raste sa:", listOf("visinom iznad površine", "dubinom", "površinom dna", "oblikom suda"), 1, "U mirnoj tečnosti važi p = p0 + ρgh."),
        Question("Arhimedova sila jednaka je:", listOf("težini tela", "težini istisnutog fluida", "pritisku na dno", "masi fluida"), 1, "Arhimedova sila jednaka je težini fluida koji je telo istisnulo."),
        Question("Paskalov zakon je osnova rada:", listOf("termometra", "hidraulične prese", "kondenzatora", "transformatora"), 1, "Pritisak se kroz zatvoren fluid prenosi podjednako, što omogućava hidraulično pojačanje sile."),
        Question("Jednačina kontinuiteta za nestlačiv fluid je:", listOf("S1v1 = S2v2", "p1v1 = p2v2", "S1/S2 = v1/v2", "S1v2 = S2v1"), 0, "Zapreminski protok Sv je stalan duž cevi."),
        Question("U užem delu cevi brzina idealnog nestlačivog fluida je:", listOf("manja", "veća", "ista", "nula"), 1, "Iz S1v1 = S2v2 sledi da manji presek znači veću brzinu."),
        Question("Bernulijeva jednačina izražava zakon održanja:", listOf("naboja", "energije", "količine kretanja samo", "mase samo"), 1, "Bernulijeva jednačina povezuje pritisak, kinetičku i potencijalnu energiju fluida po jedinici zapremine."),
        Question("Toričelijeva formula za brzinu isticanja je:", listOf("v = gh", "v = √(2gh)", "v = 2gh", "v = g/h"), 1, "Za idealno isticanje iz malog otvora važi v = √(2gh)."),
        Question("Hukov zakon glasi:", listOf("F = -kx", "F = k/x", "F = kx²", "F = mg"), 0, "U oblasti elastičnosti sila opruge proporcionalna je izduženju i suprotnog je smera."),
        Question("Površinski napon je posledica:", listOf("gravitacije", "međumolekulskih sila", "električne struje", "magnetnog polja"), 1, "Na molekule na površini deluju neuravnotežene međumolekulske sile."),
        Question("Stoksov zakon opisuje:", listOf("silу otpora viskoznog fluida", "Kulonovu silu", "Arhimedovu silu", "pritisak gasa"), 0, "Za malu kuglicu pri sporom kretanju kroz viskozan fluid važi F = 6πηrv."),
        Question("Električni naboj je:", listOf("kontinuiran bez ograničenja", "kvantovan", "uvek pozitivan", "jednak masi elektrona"), 1, "Naboj se javlja u celobrojnim umnošcima elementarnog naboja: q = ne."),
        Question("Kulonova sila između dva tačkasta naboja zavisi od rastojanja kao:", listOf("1/r", "1/r²", "r²", "r"), 1, "Kulonov zakon daje F = k|q1q2|/r²."),
        Question("Smer vektora električnog polja definiše se kao smer sile na:", listOf("negativan probni naboj", "pozitivan probni naboj", "neutralno telo", "elektron isključivo"), 1, "Vektor E ima smer sile koja bi delovala na pozitivan probni naboj."),
        Question("Potencijal tačkastog naboja je:", listOf("φ = kQ/r", "φ = kQ/r²", "φ = qU", "φ = F/q"), 0, "Za tačkasti naboj Q važi φ = kQ/r."),
        Question("Napon između dve tačke je:", listOf("zbir potencijala", "razlika potencijala", "proizvod naboja i polja", "količnik struje i otpora"), 1, "U = φ1 - φ2."),
        Question("U homogenom električnom polju između paralelnih ploča važi:", listOf("E = U/d", "E = Ud", "E = d/U", "E = U²/d"), 0, "Jačina homogenog polja jednaka je naponu po rastojanju između ploča."),
        Question("Kapacitet kondenzatora definisan je kao:", listOf("C = U/q", "C = q/U", "C = qU", "C = q²/U"), 1, "Kapacitet je odnos naboja i napona: C = q/U."),
        Question("Energija kondenzatora može se zapisati kao:", listOf("CU²/2", "CU²", "q/U", "UI"), 0, "Važi EC = CU²/2 = qU/2 = q²/(2C)."),
        Question("Kod paralelne veze kondenzatora ekvivalentni kapacitet je:", listOf("zbir kapaciteta", "manji od najmanjeg", "recipročni zbir", "uvek jednak jednom kapacitetu"), 0, "Za paralelnu vezu važi C = ΣCi."),
        Question("Jačina električne struje je:", listOf("I = Δq/Δt", "I = U/R²", "I = Rt", "I = qU"), 0, "Jačina struje je količina naboja koja prođe kroz presek u jedinici vremena."),
        Question("Omov zakon za deo kola glasi:", listOf("U = RI", "U = R/I", "I = UR", "R = UI"), 0, "Za omski otpornik važi U = RI."),
        Question("Otpor homogenog provodnika je:", listOf("R = ρl/S", "R = ρS/l", "R = l/(ρS²)", "R = ρlS"), 0, "Otpor raste sa dužinom i specifičnim otporom, a opada sa presekom."),
        Question("Džul-Lencov zakon glasi:", listOf("Q = I²Rt", "Q = IR/t", "Q = U/R", "Q = It²"), 0, "Toplota oslobođena na otporniku je Q = I²Rt."),
        Question("Za rednu vezu otpornika važi:", listOf("R = ΣRi", "1/R = Σ1/Ri", "U = 0", "I = 0"), 0, "Kod redne veze otpornosti se sabiraju, a struja je ista kroz sve otpornike."),
        Question("Za paralelnu vezu otpornika važi:", listOf("R = ΣRi", "1/R = Σ1/Ri", "R = R1R2", "I je isti u svim granama"), 1, "Kod paralelne veze napon je isti, a sabiraju se recipročni otpori."),
        Question("Prvo Kirhofovo pravilo je posledica zakona održanja:", listOf("energije", "naboja", "mase", "impulsa"), 1, "U čvoru je algebarski zbir struja nula: ΣI = 0."),
        Question("Drugo Kirhofovo pravilo je posledica zakona održanja:", listOf("energije", "naboja", "mase", "temperature"), 0, "U zatvorenoj konturi zbir elektromotornih sila i padova napona daje nulu."),
        Question("Realan izvor EMS ε, unutrašnjeg otpora r i spoljašnjeg otpora R daje struju:", listOf("I = ε/(R+r)", "I = εR/r", "I = (R+r)/ε", "I = ε/r - R"), 0, "Ukupan otpor kola je R+r, pa je I = ε/(R+r)."),
        Question("Gas primi 700 J toplote i izvrši rad 250 J. Kolika je promena unutrašnje energije?", listOf("950 J", "450 J", "250 J", "700 J"), 1, "Iz Q = ΔU + A sledi ΔU = 700 - 250 = 450 J."),
        Question("Gas se izobarski širi pri p = 2·10⁵ Pa za ΔV = 3·10⁻³ m³. Koliki rad izvrši?", listOf("60 J", "600 J", "6000 J", "0 J"), 1, "A = pΔV = 2·10⁵·3·10⁻³ = 600 J."),
        Question("Cev se suzi sa 8 cm² na 2 cm². Ako je v1 = 1 m/s, kolika je v2?", listOf("0,25 m/s", "2 m/s", "4 m/s", "8 m/s"), 2, "S1v1 = S2v2, pa v2 = 8/2·1 = 4 m/s."),
        Question("Na dubini 5 m u vodi, bez atmosferskog pritiska, koliki je hidrostatički pritisak? Uzmi ρ=1000 kg/m³ i g=10 m/s².", listOf("5 kPa", "50 kPa", "500 kPa", "5000 kPa"), 1, "p = ρgh = 1000·10·5 = 50000 Pa = 50 kPa."),
        Question("Dva naboja 2 μC i 3 μC udaljena su 0,30 m. Približna Kulonova sila je:", listOf("0,06 N", "0,6 N", "6 N", "60 N"), 1, "F = 9·10⁹·(2·10⁻⁶·3·10⁻⁶)/0,30² ≈ 0,6 N."),
        Question("Između ploča je U = 300 V i d = 1,5 cm. Koliko je E?", listOf("200 V/m", "2000 V/m", "20000 V/m", "450 V/m"), 2, "d = 0,015 m; E = U/d = 300/0,015 = 20000 V/m."),
        Question("Kondenzator C = 10 μF priključen je na U = 100 V. Kolika je energija?", listOf("0,005 J", "0,05 J", "0,5 J", "5 J"), 1, "EC = CU²/2 = 10·10⁻⁶·10000/2 = 0,05 J."),
        Question("Otpornik R = 46 Ω priključen je na 230 V. Kolika je snaga?", listOf("460 W", "920 W", "1150 W", "2300 W"), 2, "I = U/R = 5 A, pa P = UI = 230·5 = 1150 W."),
        Question("Izvor ε = 12 V i r = 1 Ω priključen je na R = 5 Ω. Kolika je struja?", listOf("1 A", "2 A", "2,4 A", "6 A"), 1, "I = ε/(R+r) = 12/6 = 2 A.")
    )
}
